language: python
notifications:
  email: false
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - cd virtual_testing_machine/src
script:
  - python -m unittest
after_success:
  - codecov
branches:
  only:
    - master