language: python
notifications:
  email: false
python:
  - "3.6"
cache: pip
install:
  - pip install --user codecov
  - pip install -r requirements.txt
script:
  - coverage run -m test.py
after_success:
  - codecov
branches:
  only:
    - master