language: python
notifications:
  email: false
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python test.py
after_success:
  - codecov
branches:
  only:
    - master
    - develop-tests